export const BOOK_SUMMARIES: Record<string, string> = {
  "Genesis": "Genesis is the origin story of everything. God creates the world, makes humanity, and watches them mess it up almost immediately. Adam and Eve get kicked out of paradise, Cain kills his brother Abel, and the world gets so corrupt God floods the whole thing — except for Noah and his family. Then God picks one man, Abraham, and makes him a promise: your descendants will become a great nation. The rest of the book follows Abraham's family — Isaac, Jacob (who gets renamed Israel), and Joseph, who gets sold into slavery by his own brothers but ends up running Egypt. It's a story about beginnings, broken people, and a God who keeps His promises even when nobody deserves it.",

  "Exodus": "Exodus is the great escape. The Israelites have been enslaved in Egypt for over 400 years, and God raises up Moses to set them free. After a dramatic showdown with Pharaoh — ten devastating plagues including rivers turning to blood, darkness covering the land, and the death of every firstborn — Pharaoh finally lets them go. God parts the Red Sea, the Israelites walk through on dry ground, and the Egyptian army gets swallowed up behind them. Then God brings them to Mount Sinai, gives Moses the Ten Commandments, and lays out the blueprint for how this nation is supposed to live. But even after all they've seen, the people build a golden calf and worship it. Exodus shows God's power to deliver and the human tendency to forget.",

  "Leviticus": "Leviticus is God's rulebook for the Israelites. It covers sacrifices, priests, clean and unclean foods, diseases, and how to live as a holy people. It's dense and detailed — but the core message is simple: God is holy, and if you want to be close to Him, you need to take that seriously. The book lays out a system of blood sacrifices to cover sin, instructions for the Day of Atonement, and moral laws about how to treat each other. It's not the easiest read, but it establishes the foundation for everything that comes after — including the idea that sin requires a sacrifice.",

  "Numbers": "Numbers follows the Israelites wandering in the desert for 40 years. It starts with a census (hence the name), then tracks the journey from Sinai toward the Promised Land. But the people keep complaining — about the food, about the leadership, about everything. When they finally reach the border of Canaan, they send in 12 spies. Ten come back terrified, and the people refuse to enter. God says fine — this entire generation will die in the wilderness except for two faithful men, Joshua and Caleb. The book is full of rebellion, consequences, and God's patience being tested over and over.",

  "Deuteronomy": "Deuteronomy is Moses' final speech to the Israelites before they enter the Promised Land. He knows he won't be going with them, so he gives them a passionate recap of everything God has done, reminds them of the laws, and pleads with them to stay faithful. Choose life, he tells them. Love God with all your heart. The book is part history lesson, part pep talk, and part farewell. Moses dies at the end on a mountaintop, looking out over the land he'll never enter. It's one of the most emotional moments in the Bible.",

  "Joshua": "Joshua picks up where Moses left off. Joshua leads the Israelites across the Jordan River and into the Promised Land. The walls of Jericho fall after they march around the city for seven days. Battle after battle, they conquer the land God promised to Abraham's descendants hundreds of years earlier. The book ends with the land divided among the twelve tribes, and Joshua giving one last challenge: choose this day who you will serve. As for me and my house, we will serve the Lord.",

  "Judges": "Judges covers one of the darkest periods in Israel's history. After Joshua dies, there's no central leader, and the people fall into a repeating cycle: they turn away from God, get oppressed by enemies, cry out for help, and God raises up a judge — a military deliverer — to save them. Rinse and repeat. The judges include Deborah, Gideon, Samson, and others. Each cycle gets worse. The book ends with the haunting summary: everyone did what was right in their own eyes. It's a raw look at what happens when people have no moral compass.",

  "Ruth": "Ruth is a short, beautiful story set during the time of the Judges. A Moabite woman named Ruth loses her husband and chooses to stay with her Israelite mother-in-law Naomi instead of going back to her own people. She follows Naomi to Bethlehem, works in the fields to survive, and catches the eye of a wealthy landowner named Boaz. Boaz marries Ruth, and they have a son who becomes the grandfather of King David. It's a love story, a loyalty story, and proof that God uses unexpected people — even outsiders — in His biggest plans.",

  "1 Samuel": "First Samuel covers the transition from judges to kings. The prophet Samuel is the last judge, and the people demand a king so they can be like other nations. God gives them Saul — tall, handsome, and initially humble. But Saul keeps disobeying God, and his reign falls apart. Meanwhile, God sends Samuel to anoint a young shepherd boy named David. David kills the giant Goliath, becomes a national hero, and Saul grows insanely jealous. The rest of the book is a cat-and-mouse chase as Saul hunts David through the wilderness. It's a story about what happens when God's anointing lifts from one person and settles on another.",

  "2 Samuel": "Second Samuel is the story of David's reign as king. He unites the nation, conquers Jerusalem, and brings the Ark of the Covenant home. God makes David an incredible promise — his throne will last forever. But David is deeply flawed. He commits adultery with Bathsheba, arranges for her husband to be killed, and his family unravels because of it. His son Absalom leads a rebellion and tries to take the throne. Despite it all, David is called a man after God's own heart — not because he was perfect, but because he always came back to God in repentance.",

  "1 Kings": "First Kings covers Solomon's glorious reign and the split of the kingdom. Solomon builds the magnificent Temple in Jerusalem and is known worldwide for his wisdom. But he marries hundreds of foreign wives who turn his heart toward idol worship. After Solomon dies, the kingdom splits in two — Israel in the north and Judah in the south. The northern kings are almost universally terrible. The prophet Elijah shows up and has an epic confrontation with the prophets of Baal on Mount Carmel, calling down fire from heaven. It's a book about how quickly greatness can crumble when you compromise.",

  "2 Kings": "Second Kings follows both kingdoms toward destruction. The northern kingdom of Israel is carried away by Assyria because they refused to turn back to God. The southern kingdom of Judah hangs on longer, with a few good kings like Hezekiah and Josiah leading spiritual revivals. But ultimately Judah falls too — Babylon destroys Jerusalem and the Temple, and the people are taken into exile. The prophet Elisha performs incredible miracles, but even his ministry can't stop the nation's downward spiral. It's a tragic end to what started with so much promise.",

  "1 Chronicles": "First Chronicles retells the history of Israel from Adam through David's reign, but from a priestly perspective. It focuses heavily on genealogies, the organization of worship, and David's preparations for building the Temple. While Second Samuel shows David's failures, Chronicles emphasizes his spiritual leadership — his psalms, his worship, his heart for God's house. David gathers materials and makes plans, even though God tells him his son Solomon will be the one to build it. It's a book about legacy and setting up the next generation for success.",

  "2 Chronicles": "Second Chronicles covers the history of Judah from Solomon through the Babylonian exile. It starts with Solomon building and dedicating the Temple in a moment of incredible glory — God's presence fills the house so powerfully the priests can't even stand. Then it traces the kings of Judah, highlighting those who sought God and prospered versus those who turned away and suffered. The book ends with Jerusalem destroyed and the people in exile, but closes with a note of hope — King Cyrus of Persia announces they can go home.",

  "Ezra": "Ezra tells the story of the Jewish people returning from exile in Babylon. King Cyrus allows them to go back to Jerusalem and rebuild the Temple. The work faces opposition and delays, but eventually the Temple is completed. The priest Ezra arrives later with a second wave of returnees and is devastated to find that the people have been intermarrying with pagan nations — the exact thing that got them in trouble before. He leads a painful but necessary reformation. It's a book about second chances and the hard work of starting over.",

  "Nehemiah": "Nehemiah is about rebuilding the walls of Jerusalem. Nehemiah is a Jewish man serving as cupbearer to the Persian king when he hears that Jerusalem's walls are still in ruins. He gets permission to go back and lead the reconstruction. Despite constant opposition — mockery, threats, and sabotage — the walls are rebuilt in just 52 days. Then Ezra reads the Law to the people, and there's a massive spiritual revival. Nehemiah shows what happens when a leader combines prayer, planning, and persistence.",

  "Esther": "Esther is a thriller set in the Persian Empire. A Jewish orphan girl named Esther becomes queen, and her cousin Mordecai uncovers a plot by a royal official named Haman to exterminate all the Jewish people. Esther has to risk her life by approaching the king uninvited to expose the plot. She does it with incredible courage, Haman is executed on the very gallows he built for Mordecai, and the Jewish people are saved. God's name is never mentioned in the book, but His fingerprints are on every page.",

  "Job": "Job is about suffering and why bad things happen to good people. Job is a righteous, wealthy man who loses everything — his children, his health, his wealth — in a series of devastating blows. His friends show up and insist he must have done something wrong to deserve it. Job maintains his innocence and demands answers from God. When God finally responds, He doesn't explain the suffering — instead He reveals His unfathomable power and wisdom. Job repents of his presumption, and God restores everything he lost, and more. It's the Bible's deepest exploration of pain, faith, and trusting God when nothing makes sense.",

  "Psalms": "Psalms is the songbook and prayer journal of the Bible. Written by David, Solomon, and others, these 150 poems and songs cover the full range of human emotion — joy, grief, anger, worship, fear, praise, and everything in between. Some are triumphant celebrations, others are desperate cries from the pit of despair. The Psalms teach us that God can handle our honest emotions, and that worship isn't just for the good days. Psalm 23 (The Lord is my shepherd) and Psalm 91 (He who dwells in the secret place) are among the most beloved passages in all of Scripture.",

  "Proverbs": "Proverbs is God's practical wisdom for everyday life. Mostly written by Solomon, it covers money, relationships, work ethic, speech, temptation, parenting, and character. The core message: the fear of the Lord is the beginning of wisdom. The book contrasts wisdom and foolishness as two paths — one leads to life, the other to destruction. It's incredibly relevant and reads like advice from a father who's seen it all and wants to save his children from making the same mistakes.",

  "Ecclesiastes": "Ecclesiastes is the Bible's most philosophical book. The writer, likely Solomon, has tried everything — wealth, pleasure, achievement, wisdom — and declares it all meaningless without God. Under the sun, nothing lasts. You work hard and someone else inherits it. You chase success and still feel empty. But the conclusion isn't despair — it's surrender. Fear God and keep His commandments, because that's the whole duty of humanity. It's a brutally honest look at life that strips away illusions and points to the only thing that truly matters.",

  "Song of Solomon": "Song of Solomon is a passionate love poem between a bride and bridegroom. It celebrates romantic love, desire, and the beauty of intimacy within commitment. The language is poetic and vivid — full of metaphors about gardens, vineyards, and fragrant spices. Many also read it as an allegory for God's love for His people or Christ's love for the church. Either way, it affirms that love and passion are gifts from God, not things to be ashamed of.",

  "Isaiah": "Isaiah is the heavyweight of the prophets. Writing over 700 years before Jesus, Isaiah delivers messages of both judgment and incredible hope. He warns Judah about coming destruction because of their sin, but also paints stunning pictures of a future Messiah — a suffering servant who would be pierced for our transgressions and by whose wounds we are healed. Isaiah's prophecies about the virgin birth, the coming king, and the new heavens and new earth are some of the most referenced passages in the New Testament. It's a massive book with a massive message: God judges sin, but He also saves.",

  "Jeremiah": "Jeremiah is known as the weeping prophet. God called him before he was born to deliver an unwelcome message to Judah: destruction is coming, and there's nothing you can do to stop it. The people rejected him, threw him in prison, and dropped him in a muddy cistern. But Jeremiah kept preaching for over 40 years. He watched Jerusalem fall to Babylon exactly as he predicted. Yet even in the darkness, Jeremiah delivered some of the most beautiful promises in Scripture — including the new covenant God would write on people's hearts. It's a book about faithful obedience when the whole world is against you.",

  "Lamentations": "Lamentations is raw grief put into poetry. Written after Jerusalem's destruction by Babylon, it's five chapters of mourning — over the ruined city, the suffering people, and the devastating consequences of sin. The writer (traditionally Jeremiah) doesn't hold back: the pain is visceral and unfiltered. But right in the middle, in chapter 3, comes one of the most famous declarations of faith: His mercies are new every morning; great is His faithfulness. Even in the ashes, hope survives.",

  "Ezekiel": "Ezekiel is a priest turned prophet who speaks to the Jewish exiles in Babylon. His book is full of bizarre and spectacular visions — wheels within wheels, a valley of dry bones that come back to life, and a future temple described in architectural detail. Ezekiel's main message: God's glory departed from the Temple because of Israel's sin, but one day it will return. The dry bones vision is one of the most powerful images in the Bible — God breathing life into dead, scattered remains and raising up a vast army. It's about resurrection, restoration, and God's power to bring the dead back to life.",

  "Daniel": "Daniel is about standing firm in a hostile culture. Taken to Babylon as a teenager, Daniel rises to the highest levels of government while refusing to compromise his faith. His friends survive a fiery furnace, and Daniel himself survives a night in a den of lions. The book also contains apocalyptic visions about future kingdoms and the end of the age — visions that connect directly to the book of Revelation. Daniel shows that you can thrive in a godless environment without selling out your convictions.",

  "Hosea": "Hosea is a love story that doubles as a sermon. God tells the prophet Hosea to marry a woman named Gomer who will be unfaithful to him. She cheats on him repeatedly, but God tells Hosea to keep pursuing her and bring her home. The whole thing is a living parable — Israel is the unfaithful spouse, and God is the heartbroken but relentless lover who refuses to give up. It's raw, painful, and one of the most powerful pictures of God's unconditional love in the entire Bible.",

  "Joel": "Joel writes about a devastating locust plague that has destroyed everything in the land, and uses it as a warning of a coming day of the Lord that will be even worse. But the heart of the message is a call to repentance — tear your hearts, not your garments, and return to God. Joel promises that if they turn back, God will restore what the locusts have eaten and pour out His Spirit on all people. That prophecy gets fulfilled in Acts 2 on the day of Pentecost.",

  "Amos": "Amos is a shepherd turned prophet who delivers a scorching message to Israel's wealthy elite. While they're living in luxury — sprawled on ivory couches, eating the finest food — the poor are being crushed. God says He despises their religious festivals and won't listen to their worship music because their hands are dirty with injustice. Let justice roll down like waters, He demands. Amos proves that God cares about how we treat people just as much as how we worship Him.",

  "Obadiah": "Obadiah is the shortest book in the Old Testament — just one chapter. It's a message against Edom, the nation descended from Esau (Jacob's brother). When Babylon destroyed Jerusalem, the Edomites didn't just watch — they gloated, looted, and turned in fleeing refugees. God says He saw all of it, and judgment is coming. The lesson: don't celebrate someone else's downfall, because what goes around comes around.",

  "Jonah": "Jonah is the story of a prophet who runs from God. God tells Jonah to preach to Nineveh, the capital of Israel's worst enemy. Jonah boards a ship going the opposite direction. God sends a massive storm, Jonah gets thrown overboard, and a giant fish swallows him for three days. When the fish spits him out, Jonah finally goes to Nineveh — and the entire city repents. Instead of being happy, Jonah is furious that God showed mercy to his enemies. The book exposes our tendency to want grace for ourselves but judgment for others.",

  "Micah": "Micah prophesies against both Israel and Judah, calling out corrupt leaders, crooked judges, and false prophets who tell people what they want to hear. But Micah also delivers some of the most beautiful prophecies in Scripture — including the prediction that the Messiah would be born in Bethlehem, and the famous summary of what God requires: do justice, love mercy, and walk humbly with your God. It's a book that balances stern warning with tender hope.",

  "Nahum": "Nahum is a prophecy of doom against Nineveh — the same city that repented in Jonah's day. But this time, about 150 years later, they've gone back to their brutal, violent ways. God declares that His patience has run out, and Nineveh will be completely destroyed. And it was — so thoroughly that for centuries, people doubted Nineveh even existed until archaeologists found its ruins. Nahum shows that God's mercy has limits when repentance is abandoned.",

  "Habakkuk": "Habakkuk is a conversation between a prophet and God. Habakkuk asks God why He's allowing so much evil and injustice in Judah. God answers: I'm sending the Babylonians to punish them. Habakkuk is horrified — the Babylonians are even worse! How can a holy God use wicked people as His instrument? God essentially says: trust Me, I have a plan, and the wicked will get theirs too. The book ends with one of the most powerful prayers in the Bible — even if everything falls apart, I will rejoice in the God of my salvation.",

  "Zephaniah": "Zephaniah warns that the day of the Lord is coming — a day of darkness, wrath, and judgment on everyone who has turned away from God. He calls out Judah for worshipping other gods, and warns surrounding nations that they'll face judgment too. But the book doesn't end in darkness. Zephaniah closes with a beautiful picture of God singing over His people with joy — the mighty warrior who saves, the loving Father who delights in His children. It's judgment and tenderness in the same breath.",

  "Haggai": "Haggai is short and to the point. The Jewish people have returned from exile and started rebuilding the Temple, but they got distracted and stopped. They're busy building their own nice houses while God's house sits in ruins. Haggai challenges them: Is it a time for you to live in paneled houses while this house lies in ruins? Consider your ways. The people listen, get back to work, and God promises His glory will fill the new Temple even greater than before.",

  "Zechariah": "Zechariah prophesies alongside Haggai to encourage the people rebuilding the Temple. His book is full of vivid visions and messianic prophecies — a king riding on a donkey, thirty pieces of silver, a pierced savior, and a day when God will stand on the Mount of Olives. Many of these prophecies were fulfilled in stunning detail by Jesus hundreds of years later. Zechariah's message: the future is bright, the Messiah is coming, and God is not done with His people.",

  "Malachi": "Malachi is the last voice before 400 years of silence between the Old and New Testaments. He confronts a spiritually lazy generation — priests offering sick animals as sacrifices, men divorcing their wives, people withholding tithes. God says: test Me in this and see if I won't throw open the floodgates of heaven. Malachi ends with a promise that Elijah will come before the great day of the Lord — a prophecy fulfilled by John the Baptist. It's a wake-up call before the longest silence in biblical history.",

  "Matthew": "Matthew presents Jesus as the long-awaited King of the Jews. It opens with a genealogy connecting Jesus to Abraham and David, proving His royal lineage. Matthew records Jesus' birth, His teachings (including the Sermon on the Mount), His miracles, and His confrontations with religious leaders. The Sermon on the Mount alone — blessed are the poor in spirit, turn the other cheek, love your enemies — is arguably the most revolutionary ethical teaching in human history. Matthew ends with Jesus' crucifixion, resurrection, and the Great Commission: go and make disciples of all nations.",

  "Mark": "Mark is the fast-paced, action-packed Gospel. It's the shortest of the four and moves at breakneck speed — the word 'immediately' appears constantly. Mark focuses on what Jesus did more than what He said. Miracle after miracle, confrontation after confrontation, Mark portrays Jesus as the powerful Son of God who came not to be served but to serve and give His life as a ransom for many. The ending is abrupt and dramatic, leaving readers with the empty tomb and a call to respond.",

  "Luke": "Luke is the most detailed Gospel, written by a physician who carefully researched everything. He emphasizes Jesus' compassion for outcasts — the poor, women, Samaritans, tax collectors, and sinners. Luke records parables found nowhere else, including the Good Samaritan and the Prodigal Son. He traces Jesus' genealogy all the way back to Adam, making the point that Jesus came for all of humanity, not just the Jewish people. Luke shows Jesus as the Savior who sees and pursues the people everyone else overlooks.",

  "John": "John is the most theological Gospel. It opens not with a birth story but with a cosmic declaration: In the beginning was the Word, and the Word was with God, and the Word was God. John focuses on seven miraculous signs and seven 'I AM' statements — I am the bread of life, the light of the world, the resurrection and the life. The whole book builds toward one purpose: that you may believe that Jesus is the Christ, the Son of God, and that by believing you may have life in His name. It's the deepest exploration of who Jesus really is.",

  "Acts": "Acts is the sequel to Luke's Gospel and covers the birth of the church. After Jesus ascends to heaven, the Holy Spirit falls on the disciples at Pentecost, and they go from hiding in a room to boldly preaching in the streets. Peter preaches and thousands are saved. Stephen becomes the first martyr. A persecutor named Saul has a dramatic encounter with Jesus on the road to Damascus and becomes the apostle Paul. The rest of the book follows Paul's missionary journeys as the gospel spreads from Jerusalem to the ends of the Roman Empire. It's the story of how a handful of ordinary people changed the world.",

  "Romans": "Romans is the apostle Paul's masterpiece — a systematic explanation of the gospel. He lays out the case that every person, Jew and Gentile alike, is guilty before God. No one is righteous. But through faith in Jesus Christ, we are justified — declared not guilty — by grace alone. Paul explains salvation, sanctification, and the incredible truth that nothing can separate us from the love of God. Chapter 8 alone contains some of the most powerful and comforting words ever written. Romans is the theological foundation of the Christian faith.",

  "1 Corinthians": "First Corinthians is Paul's letter to a messy church. The Corinthian believers were divided into cliques, tolerating sexual immorality, suing each other, and turning the Lord's Supper into a drunken party. Paul addresses every issue head-on — from marriage and singleness to spiritual gifts to the resurrection. Chapter 13, the famous love chapter (love is patient, love is kind), is the crown jewel. Paul's message: you've been set free by grace, but freedom isn't an excuse to live however you want.",

  "2 Corinthians": "Second Corinthians is Paul's most personal letter. He defends his ministry against false teachers who questioned his authority, and opens up about his suffering — beatings, shipwrecks, imprisonment, and a mysterious thorn in the flesh that God refused to remove. God's response: My grace is sufficient for you, for My power is made perfect in weakness. Paul also teaches on generous giving and the new covenant. It's a raw, vulnerable letter from a man who found his strength in his weakness.",

  "Galatians": "Galatians is Paul's most fired-up letter. False teachers were telling the Galatian believers they needed to follow Jewish law (especially circumcision) in addition to faith in Christ. Paul is furious. He argues passionately that salvation is by faith alone, not by works of the law. If you go back to law-keeping, you've fallen from grace. The fruit of the Spirit — love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control — comes from walking in the Spirit, not from following rules. It's the manifesto of Christian freedom.",

  "Ephesians": "Ephesians is Paul's letter about the church's identity and purpose. He explains the breathtaking scope of God's plan — before the foundation of the world, God chose us, adopted us, and seated us with Christ in heavenly places. Then he gets practical: put off the old self, put on the new. Be kind, forgiving, and filled with the Spirit. The letter includes the famous armor of God passage — belt of truth, breastplate of righteousness, shield of faith, sword of the Spirit. Ephesians shows who we are in Christ and how to live like it.",

  "Philippians": "Philippians is a letter of joy written from prison. Paul is chained up in Rome, facing possible execution, and yet the word 'joy' or 'rejoice' appears over a dozen times. He writes about contentment — I have learned to be content in any circumstance — and includes an incredible passage about Jesus emptying Himself, taking on human form, and being exalted above every name. Paul's secret to joy: I can do all things through Christ who strengthens me. It's proof that happiness depends on circumstances, but joy depends on Christ.",

  "Colossians": "Colossians tackles false teaching that was creeping into the church — mysticism, angel worship, and human-made rules about food and festivals. Paul responds with one of the most powerful descriptions of Jesus in the Bible: He is the image of the invisible God, the firstborn over all creation. In Him all things hold together. Paul's argument: if you have Christ, you have everything. Don't let anyone tell you that you need Christ plus something else. He is sufficient.",

  "1 Thessalonians": "First Thessalonians is one of Paul's earliest letters, written to encourage a young church facing persecution. He praises their faith, reminds them how to live to please God, and answers their big question: what happens to believers who have died? Paul gives a vivid picture of Jesus' return — the Lord Himself will descend from heaven with a shout, the dead in Christ will rise first, and then we who are alive will be caught up together with them in the clouds. It's one of the Bible's clearest passages about the second coming.",

  "2 Thessalonians": "Second Thessalonians follows up on the first letter because some believers thought Jesus had already returned and they'd missed it. Others had stopped working, figuring why bother if the end is near. Paul corrects both errors — certain events must happen first before Christ returns, and in the meantime, if you don't work, you don't eat. It's a short, practical letter about staying grounded and productive while waiting for Jesus to come back.",

  "1 Timothy": "First Timothy is Paul's mentoring letter to a young pastor. Timothy is leading the church in Ephesus, and Paul gives him practical advice on church leadership, worship, false teaching, and how to handle different age groups. Don't let anyone look down on you because you are young, Paul tells him, but set an example in speech, in conduct, in love, in faith, and in purity. It's a leadership manual for anyone who wants to serve God effectively.",

  "2 Timothy": "Second Timothy is Paul's final letter — his last words before execution. Chained in a cold Roman dungeon, Paul writes to Timothy with urgency and tenderness. He tells him to guard the faith, endure hardship like a good soldier, and preach the Word in season and out of season. Paul's farewell is unforgettable: I have fought the good fight, I have finished the race, I have kept the faith. It's the goodbye letter of a man who left everything on the field.",

  "Titus": "Titus is another pastoral letter from Paul, this time to a leader organizing churches on the island of Crete. Paul gives instructions on appointing qualified leaders and living godly lives in a corrupt culture. The Cretans had a reputation for being liars, and Paul doesn't sugarcoat it — he tells Titus to rebuke them sharply so they'll be sound in the faith. The letter emphasizes that the grace of God teaches us to say no to ungodliness and to live self-controlled, upright lives.",

  "Philemon": "Philemon is Paul's shortest letter — a personal note to a slave owner named Philemon. Philemon's runaway slave Onesimus had met Paul in prison and become a believer. Paul sends Onesimus back but asks Philemon to receive him no longer as a slave but as a brother in Christ. If he owes you anything, put it on my account, Paul writes. It's a beautiful picture of reconciliation, forgiveness, and how the gospel transforms relationships and social structures.",

  "Hebrews": "Hebrews is written to Jewish believers who were tempted to go back to Judaism under persecution. The entire letter argues that Jesus is better — better than angels, better than Moses, better than the old priesthood, better than the old covenant. Jesus is the ultimate High Priest who offered Himself as the final sacrifice. Chapter 11 is the famous faith hall of fame — Abel, Abraham, Moses, Rahab, and others who lived by faith without seeing the promises fulfilled. Hebrews calls believers to run the race with endurance, looking to Jesus.",

  "James": "James is the most practical book in the New Testament. Written by Jesus' own brother, it's a no-nonsense guide to living out your faith. Faith without works is dead, James declares — if your belief doesn't change how you live, it's not real faith. He covers controlling your tongue, showing no favoritism, resisting temptation, and being patient in suffering. He also has strong words for the rich who exploit workers. James is Christianity with its sleeves rolled up.",

  "1 Peter": "First Peter is written to believers scattered across the Roman Empire who are facing persecution. Peter encourages them to stand firm — you are a chosen people, a royal priesthood, a holy nation. He reminds them that suffering is temporary but glory is eternal. Don't be surprised by painful trials, he writes, as though something strange is happening to you. Instead, rejoice that you share in Christ's sufferings. It's a letter of hope for anyone going through the fire.",

  "2 Peter": "Second Peter warns against false teachers who will infiltrate the church with destructive heresies and immoral lifestyles. Peter reminds believers to grow in their faith and knowledge of God. He also addresses those who mock the idea of Jesus' return — the Lord is not slow in keeping His promise. He is patient, not wanting anyone to perish. The world will end with fire, Peter says, so what kind of people should you be? Holy and godly. It's a wake-up call to take the faith seriously.",

  "1 John": "First John is a letter about assurance and love. John writes so that believers can know they have eternal life — not guess, not hope, but know. He lays out clear tests: do you believe Jesus came in the flesh? Do you obey God's commands? Do you love other believers? God is light, and in Him there is no darkness. God is love, and whoever abides in love abides in God. Perfect love casts out fear. It's one of the warmest, most reassuring books in the Bible.",

  "2 John": "Second John is a brief letter warning a church (addressed as 'the elect lady') about false teachers who deny that Jesus came in the flesh. John tells them not to welcome these deceivers into their homes or even greet them, because doing so would make them partners in their evil work. It's short but sharp — truth and love must go together, and hospitality doesn't extend to those who undermine the gospel.",

  "3 John": "Third John is a personal letter commending a man named Gaius for showing hospitality to traveling missionaries, and calling out a church leader named Diotrephes who loves to be first and refuses to welcome anyone. It's a tiny window into early church dynamics — the tension between genuine servants and power-hungry leaders. John's message: imitate what is good, not what is evil.",

  "Jude": "Jude is a short, intense letter warning about false teachers who have slipped into the church unnoticed. They twist God's grace into a license for immorality and reject all authority. Jude pulls examples from the Old Testament — fallen angels, Sodom and Gomorrah, Cain, Balaam — to show that judgment is coming for them. But he ends on a high note: to Him who is able to keep you from stumbling and present you faultless before His presence with exceeding joy — to the only God our Savior be glory forever.",

  "Revelation": "Revelation is the grand finale of the Bible. Written by the apostle John from exile on the island of Patmos, it's a vision of the end of all things. Seven churches receive personal messages from Jesus. Seven seals, seven trumpets, and seven bowls of judgment are unleashed on the earth. A great dragon (Satan) wages war and loses. Babylon falls. Jesus returns on a white horse as King of Kings and Lord of Lords. Death and hell are thrown into a lake of fire. And then — a new heaven and a new earth, where God wipes away every tear, and death is no more. Revelation isn't meant to scare you. It's meant to show you who wins."
};
